platform :ios, '8.0'

target 'ExampleActivationCodeTextfield' do

    pod 'SACodedTextField', :path => '../SACodedTextField.podspec'
    
    target 'ExampleActivationCodeTextfieldTests' do
        inherit! :search_paths  # to add header search paths from target to test
    end
    
    target 'ExampleActivationCodeTextfieldUITests' do
        pod 'SACodedTextField', :path => '../SACodedTextField.podspec' #Since UI tests are an entirely separate module from the app and are not run inside the app as logic tests are
    end
    
end
